version: '3.8'

services:
  reyes-crm:
    image: reyes-crm:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reyes-crm
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
